<div id="footer" class="full-width">
	<div class="footer-container">
		<div class="footer">
			<?php //echo $this->getChildHtml() ?>
			<div class="block block-subscribe">
				<div class="block-title">
					<strong><span>Newsletter</span></strong>
				</div>
				<form action="http://localhost/fresh/magento/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
					<div class="block-content">
						<div class="form-subscribe-header">
							<label for="newsletter">Sign Up for Our Newsletter:</label>
						</div>
						<div class="input-box">
							<input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email">
						</div>
						<div class="actions">
							<button type="submit" title="Subscribe" class="button"><span><span>Subscribe</span></span></button>
						</div>
					</div>
				</form>
				<script type="text/javascript">
					//<![CDATA[
					var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
					//]]>
				</script>
			</div>
			<div class="links">
				<div class="block-title">
					<strong><span>Company</span></strong>
				</div>
				<ul>
					<li><a href="http://localhost/fresh/magento/about-magento-demo-store/">About Us</a></li>
					<li><a href="http://localhost/fresh/magento/contacts/">Contact Us</a></li>
					<li><a href="http://localhost/fresh/magento/customer-service/">Customer Service</a></li>
					<li><a href="http://localhost/fresh/magento/privacy-policy-cookie-restriction-mode/">Privacy Policy</a></li>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Quick Links</span></strong></div>
				<ul>
					<li class="first"><a href="http://localhost/fresh/magento/catalog/seo_sitemap/category/" title="Site Map">Site Map</a></li>
					<li><a href="http://localhost/fresh/magento/catalogsearch/term/popular/" title="Search Terms">Search Terms</a></li>
					<li class=" last"><a href="http://localhost/fresh/magento/catalogsearch/advanced/" title="Advanced Search">Advanced Search</a></li>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Account</span></strong></div>
				<ul>
					<li class="first"><a href="http://localhost/fresh/magento/customer/account/" title="My Account">My Account</a></li>
					<li class=" last"><a href="http://localhost/fresh/magento/sales/guest/form/" title="Orders and Returns">Orders and Returns</a></li>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Connect with us</span></strong></div>
				<a href="" class="social facebook pull-left mR10">Facebook</a>
				<a href="" class="social twitter pull-left mR10">Twitter</a>
				<a href="" class="social pinterest pull-left mR10">Pinterest</a>
				<a href="" class="social rss pull-left mR10">RSS</a>
			</div>
		</div>
	</div>
</div>
<div class="full-width">
	<address class="copyright">© <?php echo date('Y')?> Study Pravesh. All Rights Reserved.</address>
</div>