<div id="footer" class="full-width">
	<div class="footer-container">
		<div class="footer">
			<?php //echo $this->getChildHtml() ?>
			<div class="block block-subscribe">
				<div class="block-title">
					<strong><span>Newsletter</span></strong>
				</div>
				<form action="<?php echo Mage::getBaseUrl();?>newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
					<div class="block-content">
						<div class="form-subscribe-header">
							<label for="newsletter">Sign Up for Our Newsletter:</label>
						</div>
						<div class="input-box">
							<input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email">
						</div>
						<div class="actions">
							<button type="submit" title="Subscribe" class="button"><span><span>Subscribe</span></span></button>
						</div>
					</div>
				</form>
				<script type="text/javascript">
					//<![CDATA[
					var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
					//]]>
				</script>
			</div>
			<div class="links">
				<div class="block-title">
					<strong><span>Company</span></strong>
				</div>
				<ul>
					<li><a href="<?php echo Mage::getBaseUrl();?>about-us">About Us</a></li>
					<li><a href="<?php echo Mage::getBaseUrl();?>contacts">Contact Us</a></li>
                    <li><a href="<?php echo Mage::getBaseUrl();?>careers">Careers</a></li>
					<?php /*?><li><a href="<?php echo Mage::getBaseUrl();?>customer-service">Customer Service</a></li><?php */?>
					<li><a href="<?php echo Mage::getBaseUrl();?>privacy-policy">Privacy Policy</a></li>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Quick Links</span></strong></div>
				<ul>
                	<li class="first"><a href="<?php echo $this->getUrl("list-institution");?>" title="List your School, Coaching Institute, College or University">List Your Institution</a></li>
                    <li class="first"><a href="<?php echo Mage::getBaseUrl();?>schools.html">Browse Schools</a></li>
                    <li class="first"><a href="<?php echo Mage::getBaseUrl();?>coaching-institutes.html">Browse Coaching/Institutes</a></li>
                    <li class="first"><a href="<?php echo Mage::getBaseUrl();?>colleges.html">Browse Colleges</a></li>
                    <li class="first"><a href="<?php echo Mage::getBaseUrl();?>universities.html">Browse Universities</a></li>
					<?php /*?><li class="first"><a href="<?php echo Mage::getBaseUrl();?>catalog/seo_sitemap/category/" title="Site Map">Site Map</a></li>
					<li><a href="<?php echo Mage::getBaseUrl();?>catalogsearch/term/popular/" title="Search Terms">Search Terms</a></li>
					<li class=" last"><a href="<?php echo Mage::getBaseUrl();?>catalogsearch/advanced/" title="Advanced Search">Advanced Search</a></li><?php */?>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Account</span></strong></div>
				<ul>
					<li class="first"><a href="<?php echo Mage::getBaseUrl();?>customer/account/" title="My Account">My Account</a></li>
					<?php /*?><li class=" last"><a href="<?php echo Mage::getBaseUrl();?>sales/guest/form/" title="Orders and Returns">Orders and Returns</a></li><?php */?>
				</ul>
			</div>
			<div class="links">
				<div class="block-title"><strong><span>Connect with us</span></strong></div>
				<a href="https://www.facebook.com/StudyPravesh" class="social facebook pull-left mR10">Facebook</a>
				<a href="https://twitter.com/StudyPravesh" class="social twitter pull-left mR10">Twitter</a>
				<a href="https://pinterest.com/StudyPravesh" class="social pinterest pull-left mR10">Pinterest</a>
				<?php /*?><a href="" class="social rss pull-left mR10">RSS</a><?php */?>
			</div>
		</div>
	</div>
</div>
<div class="full-width">
	<address class="copyright">© <?php echo date('Y')?> Study Pravesh. All Rights Reserved.</address>
</div>