<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php /* <div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>
    </div>
</div>
*/ ?>
<?php 
$baseURL			=		Mage::getBaseUrl();
$skinURL			=		$this->getSkinUrl('images/');
?>
<div class="c-info-holder header-language-background">
    <div class="header-language-container">
        <div class="contact-info-head pull-left">
			<span class="pull-left mR10">Tel: 0141-2785628</span> <span class="pull-left mL10">Mail us : <a href="mailto:info@studypravesh.com">info@studypravesh.com</a></span>
		</div>
		<div class="login-register pull-right">
        	<?php
			if (!$this->helper('customer')->isLoggedIn()){ 
				echo '<a href="'.$this->getUrl("customer/account/login/").'">Login</a> | <a href="'.$this->getUrl("customer/account/create/").'">Signup</a>';
			}else{
				$customer 	= Mage::getSingleton('customer/session')->getCustomer();
				$firstname 	= $customer->getFirstname();
				echo 'Welcome '.$firstname.' | <a href="'.$this->getUrl('customer/account/').'">My Account</a> | <a href="'.$this->getUrl('customer/account/logout/').'">Logout</a>'; 
			} 
			?>
            |
            <a href="<?php echo $this->getUrl("list-institution");?>" title="List your School, Coaching Institute, College or University">List Institution</a>
		</div> 
    </div>
</div>

<header id="header" class="page-header full-width">
    <div class="row">
		<div class="page-header-container">
			<a class="logo pull-left" href="<?php echo $this->getUrl('') ?>">
				<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
				<img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
			</a>
			<?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
				  // See app.js for details 
				  //<div class="store-language-container"></div>
			?>
			
			
			<!-- Navigation -->
			<a class="mob-menu">Menu</a>
			<div id="header-nav" class="skip-content pull-right">
				<?php echo $this->getChildHtml('topMenu') ?>
			</div>
			<script>
				jQuery('.mob-menu').click(function(){
					if(jQuery('#header-nav').hasClass('skip-content')){
						jQuery('#header-nav').removeClass('skip-content');
						jQuery(this).css('z-index','11');
						jQuery('.logo').addClass('on-nav-logo');
						jQuery('.blink_me').addClass('on-nav-blink-me');
						jQuery('body').addClass('nav-on');
					}else{
						jQuery('#header-nav').addClass('skip-content');
						jQuery(this).css('z-index','initial');
						jQuery('.logo').removeClass('on-nav-logo');
						jQuery('.blink_me').removeClass('on-nav-blink-me');
						jQuery('body').removeClass('nav-on');
					}
				});
			</script>
			<?php /*
			<!-- Skip Links -->

			<div class="skip-links">
				<a href="#header-nav" class="skip-link skip-nav">
					<span class="icon"></span>
					<span class="label"><?php echo $this->__('Menu'); ?></span>
				</a>

				<a href="#header-search" class="skip-link skip-search">
					<span class="icon"></span>
					<span class="label"><?php echo $this->__('Search'); ?></span>
				</a>
				<div class="account-cart-wrapper">
					<a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
						<span class="icon"></span>
						<span class="label"><?php echo $this->__('Account'); ?></span>
					</a>
					<!-- Cart -->
					<div class="header-minicart">
						<?php echo $this->getChildHtml('minicart_head'); ?>
					</div>
				</div>
			</div>
			<!-- Search -->
			<div id="header-search" class="skip-content">
				<?php echo $this->getChildHtml('topSearch') ?>
			</div>
			<!-- Account -->
			<div id="header-account" class="skip-content">
				<?php echo $this->getChildHtml('topLinks') ?>
			</div>
			*/ ?>
		</div>
    </div>
</header>
<div class="header-language-background full-width">
	<div class="navigation row">
		<ul>
			<li><a href="<?php echo $this->getUrl('') ?>">Home</a></li>
			<li><a href="<?php echo $this->getUrl('about-us') ?>">About us</a></li>
			<li><a href="<?php echo $this->getUrl('contacts') ?>">Contact us</a></li>
            <li><a href="<?php echo $this->getUrl('blog') ?>">Blog</a></li>
            <li class="blink_me" style="font-size:25px; position:relative; bottom:-3px; line-height:15px;">Sabse Saste Dakhile</li>
            <li class="pull-right"><?php echo $this->getChildHtml('topSearch') ?></li>
		</ul>
	</div>
</div>
<style>
.blink_me {animation: blinker 2s linear infinite; font-style: italic; color: #ffffff; font-size: 18px; margin-left: 40px;}
@keyframes blinker { 50% { opacity: 0.0; }}
</style>
<?php if($this->getIsHomePage()) { ?>
<div class="hero-slider full-width">
	<div id="hero-slider" style="max-width:1500px; margin:0 auto;">
		<div><img src="<?php echo $this->getSkinUrl('images/homepage/hero-banner-3.jpg') ?>" alt="" style="max-width:100%" /></div>
		<div class="hidden"><img src="<?php echo $this->getSkinUrl('images/homepage/hero-banner-4.jpg') ?>" alt="" style="max-width:100%" /></div>
		<div class="hidden"><img src="<?php echo $this->getSkinUrl('images/homepage/hero-banner-5.jpg') ?>" alt="" style="max-width:100%" /></div>
		<div class="hidden"><img src="<?php echo $this->getSkinUrl('images/homepage/hero-banner-1.jpg') ?>" alt="" style="max-width:100%" /></div>
		<div class="hidden"><img src="<?php echo $this->getSkinUrl('images/homepage/hero-banner-2.jpg') ?>" alt="" style="max-width:100%" /></div>
	</div>
	<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#hero-slider').slick({
			arrows			: 	true,
			dots			: 	false,
			slidesToShow	: 	1,
			slidesToScroll	: 	1,
			autoplay		: 	true,
			autoplaySpeed	: 	5000
		});
	});
	jQuery('#hero-slider').find('div .hidden').removeClass('hidden');	//	show the remaining slides after slider initialised
	</script>
</div>
<?php } ?>
<?php echo $this->getChildHtml('topContainer'); ?>
