<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php /* <div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>
    </div>
</div>
*/ ?>
<?php 
$baseURL			=		Mage::getBaseUrl();
$skinURL			=		$this->getSkinUrl('images/');
?>
<div class="header-language-background">
    <div class="header-language-container">
        <div class="pull-left">
			<span class="pull-left mR10">Tel: +91 9983274000</span> <span class="pull-left mL10">Mail us : <a href="mailto:support@studypravesh.com">support@studypravesh.com</a></span>
		</div>
		<div class="pull-right">
			<a href="<?php echo $baseURL;?>customer/account/login/">Login</a> | <a href="<?php echo $baseURL;?>customer/account/create/">Signup</a>
 		</div>
    </div>
</div>

<header id="header" class="page-header full-width">
    <div class="row">
		<div class="page-header-container">
			<a class="logo" href="<?php echo $this->getUrl('') ?>">
				<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
				<img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
			</a>

			<?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
				  // See app.js for details 
				  //<div class="store-language-container"></div>
			?>
			
			
			<!-- Navigation -->

			<div id="header-nav" class="skip-content pull-right">
				<?php echo $this->getChildHtml('topMenu') ?>
			</div>
			
			<?php /*
			<!-- Skip Links -->

			<div class="skip-links">
				<a href="#header-nav" class="skip-link skip-nav">
					<span class="icon"></span>
					<span class="label"><?php echo $this->__('Menu'); ?></span>
				</a>

				<a href="#header-search" class="skip-link skip-search">
					<span class="icon"></span>
					<span class="label"><?php echo $this->__('Search'); ?></span>
				</a>

				<div class="account-cart-wrapper">
					<a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
						<span class="icon"></span>
						<span class="label"><?php echo $this->__('Account'); ?></span>
					</a>

					<!-- Cart -->

					<div class="header-minicart">
						<?php echo $this->getChildHtml('minicart_head'); ?>
					</div>
				</div>

			</div>


			<!-- Search -->

			<div id="header-search" class="skip-content">
				<?php echo $this->getChildHtml('topSearch') ?>
			</div>

			<!-- Account -->

			<div id="header-account" class="skip-content">
				<?php echo $this->getChildHtml('topLinks') ?>
			</div>
			
			*/ ?>
		</div>
    </div>
</header>

<?php echo $this->getChildHtml('topContainer'); ?>
