<?php if (($_products = $this->getProductCollection()) && $_products->getSize()){ ?>
<div class="full-width mB10">
	<div class="heading full-width"><?php echo $this->__('Most Popular Institutions') ?></div>
  	<?php $_collectionSize = 5;//count($_products->getItems()); echo $_collectionSize; ?>
    <div class="content-box full-width mB10">
	    <ul class="featured product-boxes products-grid" id="products-grid-table">
    <?php $i=1; foreach ($_products->getItems() as $_product){ ?>
    	<li id="td_<?php echo $i;?>" <?php if($i%5==0 or $i==$_collectionSize){echo 'class="last"';} ?> >
			<div class="li-holder">
				<div id="cont_<?php echo $i;?>" class="image-box full-width">
                	<a class="product-image" href="<?php echo $_product->getProductUrl() ?>"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(300, 200)->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'thumbnail')) ?>" /> </a>
                </div>
				<div class="detail-box full-width">
					<div class="name"><h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3></div>
				</div>
				<div class="a-center full-width p10">
				<?php if($_product->getRatingSummary()){ ?>
					<div class="full-width"><?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?></div>
				<?php } ?>
					<?php /*?><div class="full-width">
						<div class="pull-left half-width">
						<?php echo $this->getPriceHtml($_product, true) ?>
						</div>
						<?php if($_product->isSaleable()): ?>
						<button class="button pull-right" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><span><?php echo $this->__('Add to Cart') ?></span></span></span></button>
						<div class="clear"></div>
						<?php else: ?>
						<p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
						<div class="clear"></div>
						<?php endif; ?>
						<ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
						<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
						<?php endif; ?>
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
						<li class="last"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
						<?php endif; ?>
						</ul>
					</div><?php */?>
				</div>
			</div>
    	</li>
    <?php $i++; } $kol = $_collectionSize; ?>
    </ul>
	<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#products-grid-table').slick({
			arrows			: 	true,
			dots			: 	false,
			slidesToShow	: 	3,
			slidesToScroll	: 	1,
			autoplay: true,
			autoplaySpeed: 5000
		});
	});
	</script>
    </div>
</div>
<?php } ?>