<?php
	$_productCollection=$this->getLoadedProductCollection();
	$_helper = $this->helper('catalog/output');
?>
<?php if($_productCollection->count()){ ?>
<ul class="featured product-boxes" id="featured-box">
	<?php $i=0; foreach ($_productCollection as $_product){?>
	<li>
        <div class="li-holder">
            <div class="image-box full-width"><a rel="nofollow" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img-responsive"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></div>
            <div class="detail-box full-width">
                <div class="name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></div>
            </div>
            <?php //echo $this->getPriceHtml($_product, true) ?>
        </div>
    </li>
    <?php } ?>
</ul>
<?php } ?>
    
    

<script type="text/javascript">
jQuery(document).ready(function(){
	var wdth = jQuery(window).width();
	if(wdth >= 768){
		jQuery('#featured-box').slick({
			arrows			: 	true,
			dots			: 	false,
			slidesToShow	: 	3,
			slidesToScroll	: 	1,
			autoplay: true,
			autoplaySpeed: 5000
		});
	}else{
		jQuery('#featured-box').slick({
			arrows			: 	true,
			dots			: 	false,
			slidesToShow	: 	1,
			slidesToScroll	: 	1,
			autoplay: true,
			autoplaySpeed: 5000
		});
	}
});
</script>