<?php if ($_products = $this->getRecentlyViewedProducts()){ ?>
<div class="full-width mB10">           
    <div class="heading full-width"><?php echo $this->__('Recently Viewed Institutions') ?></div>
    <div class="content-box mB10">
        <ul class="featured product-boxes" id="recently-viewed-items">
        <?php foreach ($_products as $_item){ ?>
        	<li class="item">
                <div class="image-box full-width">
                	<a href="<?php echo $this->getProductUrl($_item) ?>"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(150, 150)->setWatermarkSize('30x10'); ?>" width="150" height="150" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
                </div>
                <div class="detail-box full-width">
                    <div class="name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a>
                    </div>
                </div>
            </li>
        <?php } ?>
        </ul>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
<?php } ?>
