<script type="text/javascript">
// State lists
var cities = new Array();
cities['Gujarat'] 		= new Array('Ahmedabad','Anand','Ankleshwar','Bharuch','Bhavnagar','Bhuj','Gandhinagar','Gir','Jamnagar','Kandla','Porbandar','Rajkot','Surat','Vadodara/Baroda','Valsad','Vapi','Gujarat-Other');

cities['Rajasthan'] 	= new Array('Ajmer','Jaipur','Jaisalmer','Jodhpur','Kota','Chittod','Udaipur','Rajasthan-Other');

cities['Haryana'] 	= new Array('Ambala','Chandigarh','Faridabad','Gurgaon','Hisar','Karnal','Kurukshetra','Panipat','Rohtak','Haryana-Other');

cities['Himachal Pradesh'] 	= new Array('Dalhousie','Dharmasala','Kulu/Manali','Shimla','Himachal Pradesh-Other');

cities['Jammu Kashmir'] 	= new Array('Jammu','Srinagar','Jammu and Kashmir-Other');

//cities['Haryana'] 	= new Array('');

cities['Maharashtra'] 	= new Array('Ahmednagar','Aurangabad','Jalgaon','Kolhapur','Mumbai','Mumbai Suburbs','Nagpur','Nasik','Navi Mumbai','Pune','Solapur','Maharashtra-Other');

// City lists
function setcities() {
	stateSel = document.getElementById('state');
	cityList = cities[stateSel.value];
	changeSelect('city', cityList, cityList);
}

function changeSelect(fieldID, newOptions, newValues) {
	selectField = document.getElementById(fieldID);
	selectField.options.length = 0;
	for (i=0; i<newOptions.length; i++) {
		selectField.options[selectField.length] = new Option(newOptions[i], newValues[i]);
	}
}

function addLoadEvent(func) {
	var oldonload = window.onload;
	if (typeof window.onload != 'function') {
		window.onload = func;
	}else {
		window.onload = function() {
			if (oldonload) {
				oldonload();
			}
			func();
		}
	}
}

addLoadEvent(function() {
	setcities();
});

//	Creating dynamic form action url
function OnSubmitForm(){
	
	var category	=	jQuery('#category').val();
	var course		=	jQuery('#course').val();
	var state		=	jQuery('#state').val();
	var city		=	jQuery('#city').val();
	var url			= 	category + '?course=' + course +'&state=' + state +'&city=' + city;
	//alert(url);
	jQuery("#filter_now").attr("action"); //Will retrieve it
	jQuery("#filter_now").attr("action", '<?php echo Mage::getUrl()?>' + url); //Will set it
	return true;
}

</script>

<div class="home">
  <div class="full-width">
    <div class="row p0">
      <div class="home-filter">
        <?php /*?><form action="colleges.html?cat=3&course=10&state=6&city=7" method="post"><?php */?>
        <form name="filter_now" id="filter_now" method="post" onsubmit="return OnSubmitForm();">
            <select name="cat" id="category">
                <option>Browse by</option>
                <option value="schools.html">School</option>
                <option value="coaching-institutes.html">Coaching</option>
                <option value="colleges.html">College</option>
                <option value="universities.html">University</option>
            </select>
            
            <select name="course" id="course">
                <option>Select</option>
                <option value="18">Play School</option>
                <option value="19">Primary School</option>
                <option value="20">Upper Primary School</option>

                <option value="-">---</option>
                
                <option value="">Civil Services</option>
                <option value="">Engg. Institutes</option>
                <option value="">Medical Institutes</option>
                <option value="">IIT JEE Main</option>
                <option value="">Competition Classess</option>
                <option value="">Academic Coaching Institutes</option>
                <option value="">Law Institutes</option>
                
                <option value="-">---</option>
                
                <option value="science-engg">Science & Engineering</option>
                <option value="medical-nursing">Medical/Nursing</option>
                <option value="bed">B.Ed/STC</option>
                <option value="bed">PG & Management</option>
             </select>
            <?php /*?><select name="Courses">
                <option>Select Course</option>
                <option>Option 1</option>
            </select><?php */?>
            
			<?php	//	Showing states
			$stateCollection = Mage::getModel('directory/country')->load('IN')->getRegions()->toOptionArray();
			//echo '<pre>';print_r($stateCollection);die;
			if (count($stateCollection) > 0){ ?>
                <select name="state" id="state" class="required-entry validate-select" onChange="setcities();">
                	<option>Select State</option>
                    <?php foreach($stateCollection as $state): ?>
                        <option value="<?php echo $state['label']//$state['value'] ?>"><?php echo $state['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            <?php }else{ ?>
                <input name="state" id="state" title="" value="" class="input-text required-entry"  placeholder="State"/>
            <?php } ?>
            
                        
            <select name="city" id="city" onChange="setcities();">
              <option value="">Please select a City </option>
            </select>
            
          <?php /*?><select name="fee-range">
            <option>Fee Range</option>
            <option>Option 1</option>
          </select><?php */?>
          <input type="submit" value="Filter Now" name="filter" />
        </form>
      </div>
    </div>
  </div>
  <div class="main-content full-width">
    <div class="full-width mB10">
      <div class="row p0">
        <div class="left-content">
			<div class="full-width mB10">
			  <div class="heading full-width">Featured Schools, Colleges, Institutes and Universities</div>
        	<div class="content-box full-width mB10">
				<ul class="featured product-boxes" id="featured-box">
        <?php 
		if(($_products = Mage::helper('sarah')->getProductsFromCategory('18')) && $_products->getSize()){ 	
			foreach($_products->getItems() as $_product){?>
                <li>
                    <div class="li-holder">
                        <div class="image-box full-width"><a rel="nofollow" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(450); ?>" class="img-responsive" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></div>
                        <div class="detail-box full-width">
                            <div class="name"><?php echo $this->htmlEscape($_product->getName()) ?></div>
                            <div class="price-box"><?php echo $this->helper('core')->currency($_product->getPrice(),true,false) ?>
                            </div>
                            <?php /*?><a rel="nofollow" href="<?php echo $_product->getProductUrl(); ?>">
						<p class="fontsize-type1 low-margin-bottom"><?php echo  Mage::helper('core/string')->truncate($this->stripTags($_product->getShortDescription(), null, true), $length = 45, $etc = '...'); ?></p>
					</a><?php */?>
                        </div>
                    </div>
                </li>
        <?php }
		} ?>
				</ul>
				<script type="text/javascript">
				jQuery(document).ready(function(){
					jQuery('#featured-box').slick({
						arrows			: 	true,
						dots			: 	false,
						slidesToShow	: 	3,
						slidesToScroll	: 	1,
						autoplay: true,
						autoplaySpeed: 5000
					});
				});
				</script>
			  </div>
			</div>
        </div>
        <div class="right-content">
          <div class="heading full-width">News &amp; Announcements</div>
          <div class="content-box">
            <div class="full-width border-box-1px p10">
              <ul class="news">
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="how-it-works full-width mB10 mT10">
      <div class="row p0"><img style="max-width: 100%;" alt="" src="{{skin url='images/how-it-works.jpg'}}" /></div>
    </div>
    
    <div class="full-width mT10">
      <div class="row p0">
        <div class="left-content">
        	<?php echo $this->getLayout()->createBlock('catalog/product_mostviewed')->setTemplate('catalog/product/mostviewed.phtml')->toHtml();?>
            <?php echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed.phtml')->toHtml(); ?>
        </div>
        
        <div class="right-content">
          <?php echo $this->getLayout()->createBlock('testimonial/sidebar')->setTemplate('testimonial/sidebar/slider.phtml')->toHtml();?>
        </div>
        
      </div>
    </div>
  </div>
</div>
