<?php
$baseURL			=		Mage::getBaseUrl();
$skinURL			=		$this->getSkinUrl('images/');
?>
<script type="text/javascript">
//	Creating dynamic form action url
function OnSubmitForm(){
	var category	=	jQuery('#category').val();
	var categoryUrl = 	'schools.html';
	if(category==1){
		categoryUrl = 	'schools.html';
	}else if(category==2){
		categoryUrl = 	'coaching-institutes.html';
	}else if(category==3){
		categoryUrl = 	'colleges.html';
	}else if(category==4){
		categoryUrl = 	'universities.html';
	}
	var course		=	jQuery('#course').val();
	var state		=	jQuery('#state').val();
	var city		=	jQuery('#city').val();
	var url			= 	categoryUrl + '?course=' + course +'&state=' + state +'&city=' + city;
	//alert(url);
	jQuery("#filterFrm").attr("action");
	jQuery("#filterFrm").attr("action", '<?php echo Mage::getUrl()?>' + url);
	return true;
}
</script>

<div class="home">
  <div class="full-width">
    <div class="row p0">
      <div class="home-filter">
        <form name="filterFrm" id="filterFrm" method="post" onsubmit="return OnSubmitForm();">
            <div class="inputBox">
				<select name="category" id="category" class="required-entry validate-select">
					<option value="">Browse by</option>
					<option value="1">School</option>
					<option value="2">Coaching/Institutes</option>
					<option value="3">College</option>
					<option value="4">University</option>
				</select>
			</div>
			<script type="text/javascript">
				Event.observe($('category'), 'change', function(event) {
					jQuery('#course').attr('disabled','disabled');
					jQuery('#course').find('option:selected').html('Please Wait...');
					var action 		= 	"<?php echo $this->getUrl('querymanager/index/getCourses'); ?>";
					var categoryId 	= 	$('category').value;	
					var request 	= 	new Ajax.Request(action,
						{
							method: 'GET',
							parameters: {category_id: categoryId},
							onComplete: function(data) {
								//alert(data.responseText);
								jQuery('#course').removeAttr('disabled');
								$('course').replace('<select id="course" name="course" class="required-entry validate-select">' + '<option value="">Select a Course</option>' + data.responseText + '</select>');
							},
							onSuccess: function (data) {
								
							},
							onFailure: ''
						}
					);
				});
			</script>
            <div class="inputBox">
            <?php	//	Showing courses
			$attribute 			= 	Mage::getModel('eav/config')->getAttribute('catalog_product', 'course');
			$courseCollection 	= 	$attribute->getSource()->getAllOptions(true, true);
			//echo '<pre>';print_r($courseCollection);die;
			if (count($courseCollection) > 0){ ?>
                <select name="course" id="course" class="required-entry validate-select">
                	<option value="">Select a Course</option>
                    <?php 
						foreach($courseCollection as $course){
							if($course['label']){ ?>
                        		<option value="<?php echo $course['value'];?>"><?php echo $course['label'] ?></option>
                    	<?php }
						} 
					?>
                </select>
            <?php }else{ ?>
                <input name="course" id="course" title="" value="" class="input-text required-entry"  placeholder="Course"/>
            <?php } ?>
            </div>
            <div class="inputBox">
			<?php	//	Showing states
			$attribute 	= 	Mage::getModel('eav/config')->getAttribute('catalog_product', 'state');
			$stateCollection = 	$attribute->getSource()->getAllOptions(true, true);
			//echo '<pre>';print_r($stateCollection);die;
			if (count($stateCollection) > 0){ ?>
                <select name="state" id="state" class="required-entry validate-select">
                	<option value="">Select a State</option>
                    <?php 
						foreach($stateCollection as $state){
							if($state['label']){ ?>
                        		<option value="<?php echo $state['value'];?>"><?php echo $state['label'] ?></option>
                    	<?php }
						} 
					?>
                </select>
            <?php }else{ ?>
                <input name="state" id="state" title="" value="" class="input-text required-entry"  placeholder="State"/>
            <?php } ?>
            </div>
			<div class="inputBox">
            <select name="city" id="city" class="required-entry validate-select" disabled="disabled">
              <option value="">Select a City </option>
            </select>
            </div>
            <script type="text/javascript">
			Event.observe($('state'), 'change', function(event) {
				jQuery('#city').find('option:selected').html('Please Wait...');
				jQuery('#city').attr('disabled','disabled');
				var action 	= 	"<?php echo $this->getUrl('querymanager/index/getCities'); ?>";
				var stateId = 	$('state').value;
				var request = 	new Ajax.Request(action,
					{
						method: 'GET',
						parameters: {state_id: stateId},
						onComplete: function(data) {
							//alert(data.responseText);
							$('city').replace('<select id="city" name="city" class="required-entry validate-select">' + '<option value="">Select a City</option>' + data.responseText + '</select>');
						},
						onSuccess: function (data) {
							
						},
						onFailure: ''
					}
				);
			});
			</script>
          <input type="submit" value="Filter Now" name="filter" />
        </form>
        <script type="text/javascript">
        //	Handle form submit
        //< ![CDATA[
        var customForm = new VarienForm('filterFrm', true);
        //]]>
        </script>
      </div>
    </div>
  </div>
  <div class="main-content full-width">
    <div class="full-width mB10">
      <div class="row p0">
        <div class="left-content">
			<div class="full-width mB10">
			  	<div class="heading full-width">Featured Schools, Colleges, Institutes and Universities</div>
        			<div class="content-box full-width mB10">
						<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('homepage/featured.phtml')->toHtml(); ?>
                        <?php echo $this->getLayout()->createBlock('featuredproducts/product_list_homepage')->setTemplate('featuredproducts/list/homepage.phtml')->toHtml(); ?>
					</div>
				</div>
        	</div>
        <div class="right-content">
          <div class="heading full-width">News &amp; Announcements</div>
          <div class="content-box">
            <div class="full-width border-box-1px p10" style="height: 292px; overflow-y: scroll; overflow-x: hidden; border:none;">
              <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('aw_blog/latest.phtml')->toHtml(); ?>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="how-it-works full-width mB10 mT10 pB10 pT10">
      <div class="row p0">
		<div class="full-width p10 hw-heading"><span>How it Works</span></div>
		<div class="hiw">
			<img style="max-width:100%; margin:0 auto" alt="" src="<?php echo $skinURL.'hw-1.jpg';?>" />
			<div class="full-width p10 hw-title"><a href="<?php echo $this->getUrl("customer/account/create/")?>">Student Signup</a></div>
			<div class="full-width p10 hw-text">
				Create a new account to get started. Registration is free for all students.
			</div>
			<div class="full-width p10 hw-pro"><span><a href="<?php echo $this->getUrl("customer/account/create/")?>">01</a></span></div>
		</div>
		<div class="hiw">
			<img style="max-width:100%; margin:0 auto" alt="" src="<?php echo $skinURL.'hw-2.jpg';?>" />
			<div class="full-width p10 hw-title"><a href="<?php echo $this->getUrl("coaching-institutes.html")?>">Choose Institutions</a></div>
			<div class="full-width p10 hw-text">
				Search institutions according to your requirement.
			</div>
			<div class="full-width p10 hw-pro"><span><a href="<?php echo $this->getUrl("coaching-institutes.html")?>">02</a></span></div>
		</div>
		<div class="hiw">
			<img style="max-width:100%; margin:0 auto" alt="" src="<?php echo $skinURL.'hw-3.jpg';?>" />
			<div class="full-width p10 hw-title"><a href="<?php echo $this->getUrl("checkout/cart")?>">Get Admission</a></div>
			<div class="full-width p10 hw-text">
				Apply with your details and submit the fee. It's a hassle free experience thereafter.
			</div>
			<div class="full-width p10 hw-pro"><span><a href="<?php echo $this->getUrl("checkout/cart")?>">03</a></span></div>
		</div>
	  </div>
    </div>
    <div class="full-width mT10">
      <div class="row p0">
        <div class="left-content">
        	<?php echo $this->getLayout()->createBlock('catalog/product_mostviewed')->setTemplate('catalog/product/mostviewed.phtml')->toHtml();?>
            <?php echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed_homepage.phtml')->toHtml(); ?>
        </div>
        <div class="right-content">
          <?php echo $this->getLayout()->createBlock('testimonial/sidebar')->setTemplate('testimonial/sidebar/slider.phtml')->toHtml();?>
        </div>
      </div>
    </div>
  </div>
</div>
