<div class="home">
  <div class="full-width">
    <div class="row p0">
      <div class="home-filter">
        <form action="colleges.html?cat=3&course=10&state=6&city=7" method="post">
            <select name="cat">
                <option>Browse by</option>
                <option value="21">School</option>
                <option value="11">Coaching</option>
                <option value="3">College</option>
                <option value="24">University</option>
            </select>
            
            <select name="course">
                <option>Select</option>
                <option value="18">Play School</option>
                <option value="19">Primary School</option>
                <option value="20">Upper Primary School</option>

                <option value="-">---</option>
                
                <option value="">Civil Services</option>
                <option value="">Engg. Institutes</option>
                <option value="">Medical Institutes</option>
                <option value="">IIT JEE Main</option>
                <option value="">Competition Classess</option>
                <option value="">Academic Coaching Institutes</option>
                <option value="">Law Institutes</option>
                
                <option value="-">---</option>
                
                <option value="science-engg">Science & Engineering</option>
                <option value="medical-nursing">Medical/Nursing</option>
                <option value="bed">B.Ed/STC</option>
                <option value="bed">PG & Management</option>
             </select>
            <?php /*?><select name="Courses">
                <option>Select Course</option>
                <option>Option 1</option>
            </select><?php */?>
            
			<?php	//	Showing states
			$stateCollection = Mage::getModel('directory/country')->load('IN')->getRegions()->toOptionArray();
			//echo '<pre>';print_r($stateCollection);die;
			if (count($stateCollection) > 0){ ?>
                <select name="state" id="state" class="required-entry validate-select">
                	<option>Select State</option>
                    <?php foreach($stateCollection as $state): ?>
                        <option value="<?php echo $state['label']//$state['value'] ?>"><?php echo $state['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            <?php }else{ ?>
                <input name="state" id="state" title="" value="" class="input-text required-entry"  placeholder="State"/>
            <?php } ?>
            
            <select name="city">
                <option>Select City</option>
                <option>Option 1</option>
            </select>
            
          <?php /*?><select name="fee-range">
            <option>Fee Range</option>
            <option>Option 1</option>
          </select><?php */?>
          <input type="submit" value="Filter Now" name="filter" />
        </form>
      </div>
    </div>
  </div>
  <div class="main-content full-width">
    <div class="full-width mB10">
      <div class="row p0">
        <div class="left-content">
			<div class="full-width mB10">
			  <div class="heading full-width">Featured Schools, Colleges, Institutes and Universities</div>
			  <div class="content-box mB10">
				<ul class="featured product-boxes">
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				  <li>
					<div class="image-box full-width"><img title="Linen Blazer" alt="Linen Blazer" src="{{media url='wysiwyg/Womenpantsimg.jpg'}}" /></div>
					<div class="detail-box full-width">
					  <div class="name">H.R. Institute of Technology, Ghaziabad</div>
					</div>
				  </li>
				</ul>
			  </div>
			</div>
        </div>
        <div class="right-content">
          <div class="heading full-width">News &amp; Announcements</div>
          <div class="content-box">
            <div class="full-width border-box-1px p10">
              <ul class="news">
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
                <li>
                  <div class="date full-width mB10"><span>Oct 09, 2015</span></div>
                  <div class="text full-width mB10">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="how-it-works full-width mB10 mT10">
      <div class="row p0"><img style="max-width: 100%;" alt="" src="{{skin url='images/how-it-works.jpg'}}" /></div>
    </div>
    
    <div class="full-width mT10">
      <div class="row p0">
        <div class="left-content">
        	<?php echo $this->getLayout()->createBlock('catalog/product_mostviewed')->setTemplate('catalog/product/mostviewed.phtml')->toHtml();?>
            <?php echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed.phtml')->toHtml(); ?>
        </div>
        <div class="right-content">
          <div class="heading full-width">Testimonials</div>
          <div class="content-box">
            <div class="full-width border-box-1px p10">
              <ul class="testimonials">
                <li>
                  <div class="tm-img full-width"><span><img style="max-width: 100%;" alt="" src="<?php echo $this->getSkinUrl('images/tm-img.jpg');?>" /></span></div>
                  <div class="tm-detail full-width">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur, Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temlor in kreprehenderit in voluptate velit esse cillium dolore eu fugiat nulla pariatur</div>
                  <div class="tm-name full-width">-Nick</div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
