<ul class="featured product-boxes" id="featured-box">
<?php 
	if(($_products = Mage::helper('sarah')->getProductsFromCategory('18')) && $_products->getSize()){ 	
		foreach($_products->getItems() as $_product){?>
		<li>
    		<div class="li-holder">
      			<div class="image-box full-width"><a rel="nofollow" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 200)->setWatermarkSize('30x10'); ?>" class="img-responsive" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></div>
      			<div class="detail-box full-width">
                    <div class="name"><?php echo $this->htmlEscape($_product->getName()) ?></div>
                    <div class="price-box"><?php echo $this->helper('core')->currency($_product->getPrice(),true,false) ?> </div>
        <?php /*?><a rel="nofollow" href="<?php echo $_product->getProductUrl(); ?>">
						<p class="fontsize-type1 low-margin-bottom"><?php echo  Mage::helper('core/string')->truncate($this->stripTags($_product->getShortDescription(), null, true), $length = 45, $etc = '...'); ?></p>
					</a><?php */?>
      			</div>
    		</div>
  		</li>
	<?php }
	} ?>
</ul>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('#featured-box').slick({
		arrows			: 	true,
		dots			: 	false,
		slidesToShow	: 	3,
		slidesToScroll	: 	1,
		autoplay: true,
		autoplaySpeed: 5000
	});
});
</script>