<div class="full-width quick-apply" id="ajaxData">
    <div class="full-width" style="border:1px solid #cccccc;">
        <div class="heading full-width"><h1>Query for Apply</h1></div>
        <form method="post" name="queryFrm" id="queryFrm" action="">
        <div class="full-width pL10 pR10">
            <div class="input-box full-width">
                <label>Your Name <span class="star">*</span></label>
                <input class="input-text required-entry" type="text" value="" placeholder="Your Name" id="name" name="name">
            </div>
            
            <div class="input-box full-width">
                <label>Email Id <span class="star">*</span></label>
                <input class="required-entry validate-email" type="email" value="" placeholder="Email" id="email" name="email">
            </div>
            
            <div class="input-box full-width">
                <label>State <span class="star">*</span></label>
                <?php	$stateCollection = Mage::getModel('directory/country')->load('IN')->getRegions()->toOptionArray();
					//echo '<pre>';print_r($stateCollection);die;
					if (count($stateCollection) > 0){ ?>
				  <select class="validate-select" name="state" id="state" requried="">
                  	<option value="">Please Select State</option>
					<?php foreach($stateCollection as $state): ?>
					<option value="<?php echo $state['value'] ?>"> <?php echo $state['label'] ?> </option>
					<?php endforeach; ?>
				  </select>
				<?php } ?>
            </div>
            <div class="input-box full-width">
                <label>City <span class="star">*</span></label>
                <select class="validate-select" name="city" id="city">
                    <option value="">Please Select City</option>
                </select>
            </div>
            <div class="input-box full-width">
                <label>Mobile </label>
                <input type="text" value="" id="mobile" placeholder="Mobile" name="mobile">
            </div>
            <div class="input-box full-width">
                <label>Course <span class="star">*</span></label>
                <input type="text" id="courses" placeholder="Type Your Course Name Here" name="courses">
            </div>
            <div class="input-box full-width">
                <label>Message <span class="star">*</span></label>
                <textarea class="required-entry" id="message" name="message"></textarea>
            </div>
            
            <div class="full-width pL10 pR10 pB10">
				<input class="btn button pull-right" type="submit" name="submit" value="Enquire Now" />
			</div>
            
		</div>
      </form>
    </div>
</div>
<script type="text/javascript">
	//	Calling states cities
	Event.observe($('state'), 'change', function(event) {
		var action = "<?php echo $this->getUrl('directorycity/index/getCities'); ?>";
		var stateId = $('state').value;
		var request = new Ajax.Request(action,
			{
				method: 'GET',
				parameters: {state_id: stateId},
				onComplete: function(data) {
					//alert(data.responseText);
					$('city').replace('<select id="city" name="city" class="validate-select">' + '<option value="">Please Select City</option>' + data.responseText + '</select>');
				},
				onSuccess: function (data) {
				},
				onFailure: ''
			}
		);
	});
	
	
	//	Handle ajax form submit
	//< ![CDATA[
	var customForm = new VarienForm('queryFrm', true);
	//]]>
	<?php /*?>jQuery('#queryFrm').on('submit', function(e) {
		e.preventDefault();
		if(customForm.validator.validate()) {
			var url =  '<?php echo Mage::getBaseUrl();?>querymanager/index/ajaxPost';
			var dataString = jQuery(this).serialize();
			jQuery.ajax({
				type: 'POST',
				url: url,
				data: dataString
			})
			.done(function(result,textStatus){
				if(textStatus == 'success'){          
					jQuery("#ajaxData").html(result);
				}
			})
			.fail(function(){         
				// just in case posting your form failed
				//alert( "Posting failed." );             
			});			 
			// to prevent refreshing the whole page page
			return false;
		}
	});	<?php */?>
</script>